# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.runbook_processes_api import RunbookProcessesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRunbookProcessesApi(unittest.TestCase):
    """RunbookProcessesApi unit test stubs"""

    def setUp(self):
        self.api = api.runbook_processes_api.RunbookProcessesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_runbook_process_by_id(self):
        """Test case for get_runbook_process_by_id

        Get a RunbookProcessResource by ID  # noqa: E501
        """
        pass

    def test_get_runbook_process_by_id_spaces(self):
        """Test case for get_runbook_process_by_id_spaces

        Get a RunbookProcessResource by ID  # noqa: E501
        """
        pass

    def test_get_runbook_snapshot_template_for_runbook_step(self):
        """Test case for get_runbook_snapshot_template_for_runbook_step

        """
        pass

    def test_get_runbook_snapshot_template_for_runbook_step_spaces(self):
        """Test case for get_runbook_snapshot_template_for_runbook_step_spaces

        """
        pass

    def test_index_runbook_processes(self):
        """Test case for index_runbook_processes

        Get a list of RunbookProcessResources  # noqa: E501
        """
        pass

    def test_index_runbook_processes_spaces(self):
        """Test case for index_runbook_processes_spaces

        Get a list of RunbookProcessResources  # noqa: E501
        """
        pass

    def test_update_runbook_process(self):
        """Test case for update_runbook_process

        """
        pass

    def test_update_runbook_process_spaces(self):
        """Test case for update_runbook_process_spaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
