# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.spaces_api import SpacesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSpacesApi(unittest.TestCase):
    """SpacesApi unit test stubs"""

    def setUp(self):
        self.api = api.spaces_api.SpacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_space(self):
        """Test case for create_space

        """
        pass

    def test_create_space_logo(self):
        """Test case for create_space_logo

        """
        pass

    def test_delete_space(self):
        """Test case for delete_space

        """
        pass

    def test_get_space_by_id(self):
        """Test case for get_space_by_id

        Get a SpaceResource by ID  # noqa: E501
        """
        pass

    def test_get_space_logo(self):
        """Test case for get_space_logo

        """
        pass

    def test_index_spaces(self):
        """Test case for index_spaces

        Get a list of SpaceResources  # noqa: E501
        """
        pass

    def test_list_all_spaces(self):
        """Test case for list_all_spaces

        Get a list of SpaceResources  # noqa: E501
        """
        pass

    def test_update_modify_space(self):
        """Test case for update_modify_space

        """
        pass

    def test_update_space_logo(self):
        """Test case for update_space_logo

        """
        pass


if __name__ == '__main__':
    unittest.main()
