# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.deployment_action_resource import DeploymentActionResource  # noqa: E501
from swagger_client.rest import ApiException


class TestDeploymentActionResource(unittest.TestCase):
    """DeploymentActionResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeploymentActionResource(self):
        """Test DeploymentActionResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.deployment_action_resource.DeploymentActionResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
