# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.action_templates_api import ActionTemplatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestActionTemplatesApi(unittest.TestCase):
    """ActionTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = api.action_templates_api.ActionTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_action_template(self):
        """Test case for create_action_template

        Create a ActionTemplateResource  # noqa: E501
        """
        pass

    def test_create_action_template_actions(self):
        """Test case for create_action_template_actions

        """
        pass

    def test_create_action_template_actions_spaces(self):
        """Test case for create_action_template_actions_spaces

        """
        pass

    def test_create_action_template_logo(self):
        """Test case for create_action_template_logo

        """
        pass

    def test_create_action_template_logo_spaces(self):
        """Test case for create_action_template_logo_spaces

        """
        pass

    def test_create_action_template_spaces(self):
        """Test case for create_action_template_spaces

        Create a ActionTemplateResource  # noqa: E501
        """
        pass

    def test_delete_action_template(self):
        """Test case for delete_action_template

        Delete a ActionTemplateResource by ID  # noqa: E501
        """
        pass

    def test_delete_action_template_spaces(self):
        """Test case for delete_action_template_spaces

        Delete a ActionTemplateResource by ID  # noqa: E501
        """
        pass

    def test_get_action_template_by_id(self):
        """Test case for get_action_template_by_id

        Get a ActionTemplateResource by ID  # noqa: E501
        """
        pass

    def test_get_action_template_by_id_spaces(self):
        """Test case for get_action_template_by_id_spaces

        Get a ActionTemplateResource by ID  # noqa: E501
        """
        pass

    def test_get_action_template_categories(self):
        """Test case for get_action_template_categories

        """
        pass

    def test_get_action_template_categories_spaces(self):
        """Test case for get_action_template_categories_spaces

        """
        pass

    def test_get_action_template_logo(self):
        """Test case for get_action_template_logo

        """
        pass

    def test_get_action_template_logo_spaces(self):
        """Test case for get_action_template_logo_spaces

        """
        pass

    def test_get_action_template_logo_version(self):
        """Test case for get_action_template_logo_version

        """
        pass

    def test_get_action_template_logo_version_spaces(self):
        """Test case for get_action_template_logo_version_spaces

        """
        pass

    def test_get_action_template_usage(self):
        """Test case for get_action_template_usage

        """
        pass

    def test_get_action_template_usage_spaces(self):
        """Test case for get_action_template_usage_spaces

        """
        pass

    def test_get_action_template_version(self):
        """Test case for get_action_template_version

        """
        pass

    def test_get_action_template_version_spaces(self):
        """Test case for get_action_template_version_spaces

        """
        pass

    def test_get_action_templates_search(self):
        """Test case for get_action_templates_search

        """
        pass

    def test_get_action_templates_search_spaces(self):
        """Test case for get_action_templates_search_spaces

        """
        pass

    def test_index_action_templates(self):
        """Test case for index_action_templates

        Get a list of ActionTemplateResources  # noqa: E501
        """
        pass

    def test_index_action_templates_spaces(self):
        """Test case for index_action_templates_spaces

        Get a list of ActionTemplateResources  # noqa: E501
        """
        pass

    def test_list_all_action_templates(self):
        """Test case for list_all_action_templates

        Get a list of ActionTemplateResources  # noqa: E501
        """
        pass

    def test_list_all_action_templates_spaces(self):
        """Test case for list_all_action_templates_spaces

        Get a list of ActionTemplateResources  # noqa: E501
        """
        pass

    def test_update_action_template(self):
        """Test case for update_action_template

        Modify a ActionTemplateResource by ID  # noqa: E501
        """
        pass

    def test_update_action_template_logo(self):
        """Test case for update_action_template_logo

        """
        pass

    def test_update_action_template_logo_spaces(self):
        """Test case for update_action_template_logo_spaces

        """
        pass

    def test_update_action_template_spaces(self):
        """Test case for update_action_template_spaces

        Modify a ActionTemplateResource by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
