# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.reporting_api import ReportingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportingApi(unittest.TestCase):
    """ReportingApi unit test stubs"""

    def setUp(self):
        self.api = api.reporting_api.ReportingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_deployments_by_project_report(self):
        """Test case for get_deployments_by_project_report

        """
        pass

    def test_get_deployments_by_project_report_spaces(self):
        """Test case for get_deployments_by_project_report_spaces

        """
        pass

    def test_get_deployments_xml(self):
        """Test case for get_deployments_xml

        """
        pass

    def test_get_deployments_xml_spaces(self):
        """Test case for get_deployments_xml_spaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
