# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.events_api import EventsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_event_by_id(self):
        """Test case for get_event_by_id

        Get a EventResource by ID  # noqa: E501
        """
        pass

    def test_get_event_by_id_spaces(self):
        """Test case for get_event_by_id_spaces

        Get a EventResource by ID  # noqa: E501
        """
        pass

    def test_get_list_event_agents(self):
        """Test case for get_list_event_agents

        """
        pass

    def test_get_list_event_agents_spaces(self):
        """Test case for get_list_event_agents_spaces

        """
        pass

    def test_get_list_event_categories(self):
        """Test case for get_list_event_categories

        """
        pass

    def test_get_list_event_categories_spaces(self):
        """Test case for get_list_event_categories_spaces

        """
        pass

    def test_get_list_event_document_types(self):
        """Test case for get_list_event_document_types

        """
        pass

    def test_get_list_event_document_types_spaces(self):
        """Test case for get_list_event_document_types_spaces

        """
        pass

    def test_get_list_event_groups(self):
        """Test case for get_list_event_groups

        """
        pass

    def test_get_list_event_groups_spaces(self):
        """Test case for get_list_event_groups_spaces

        """
        pass

    def test_get_list_events(self):
        """Test case for get_list_events

        """
        pass

    def test_get_list_events_spaces(self):
        """Test case for get_list_events_spaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
