# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.tenants_api import TenantsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self):
        self.api = api.tenants_api.TenantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tenant(self):
        """Test case for create_tenant

        Create a TenantResource  # noqa: E501
        """
        pass

    def test_create_tenant_logo(self):
        """Test case for create_tenant_logo

        """
        pass

    def test_create_tenant_logo_spaces(self):
        """Test case for create_tenant_logo_spaces

        """
        pass

    def test_create_tenant_spaces(self):
        """Test case for create_tenant_spaces

        Create a TenantResource  # noqa: E501
        """
        pass

    def test_create_tenant_variables(self):
        """Test case for create_tenant_variables

        """
        pass

    def test_create_tenant_variables_spaces(self):
        """Test case for create_tenant_variables_spaces

        """
        pass

    def test_delete_tenant(self):
        """Test case for delete_tenant

        Delete a TenantResource by ID  # noqa: E501
        """
        pass

    def test_delete_tenant_spaces(self):
        """Test case for delete_tenant_spaces

        Delete a TenantResource by ID  # noqa: E501
        """
        pass

    def test_get_tenant_by_id(self):
        """Test case for get_tenant_by_id

        Get a TenantResource by ID  # noqa: E501
        """
        pass

    def test_get_tenant_by_id_spaces(self):
        """Test case for get_tenant_by_id_spaces

        Get a TenantResource by ID  # noqa: E501
        """
        pass

    def test_get_tenant_logo(self):
        """Test case for get_tenant_logo

        """
        pass

    def test_get_tenant_logo_spaces(self):
        """Test case for get_tenant_logo_spaces

        """
        pass

    def test_get_tenant_tag_test(self):
        """Test case for get_tenant_tag_test

        """
        pass

    def test_get_tenant_tag_test_spaces(self):
        """Test case for get_tenant_tag_test_spaces

        """
        pass

    def test_get_tenant_variable_set_test(self):
        """Test case for get_tenant_variable_set_test

        """
        pass

    def test_get_tenant_variable_set_test_spaces(self):
        """Test case for get_tenant_variable_set_test_spaces

        """
        pass

    def test_get_tenant_variables(self):
        """Test case for get_tenant_variables

        """
        pass

    def test_get_tenant_variables_missing(self):
        """Test case for get_tenant_variables_missing

        """
        pass

    def test_get_tenant_variables_missing_spaces(self):
        """Test case for get_tenant_variables_missing_spaces

        """
        pass

    def test_get_tenant_variables_spaces(self):
        """Test case for get_tenant_variables_spaces

        """
        pass

    def test_get_tenants_configuration(self):
        """Test case for get_tenants_configuration

        """
        pass

    def test_get_tenants_configuration_spaces(self):
        """Test case for get_tenants_configuration_spaces

        """
        pass

    def test_index_tenants(self):
        """Test case for index_tenants

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_index_tenants_spaces(self):
        """Test case for index_tenants_spaces

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_list_all_tenants(self):
        """Test case for list_all_tenants

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_list_all_tenants_spaces(self):
        """Test case for list_all_tenants_spaces

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_update_tenant(self):
        """Test case for update_tenant

        Modify a TenantResource by ID  # noqa: E501
        """
        pass

    def test_update_tenant_logo(self):
        """Test case for update_tenant_logo

        """
        pass

    def test_update_tenant_logo_spaces(self):
        """Test case for update_tenant_logo_spaces

        """
        pass

    def test_update_tenant_spaces(self):
        """Test case for update_tenant_spaces

        Modify a TenantResource by ID  # noqa: E501
        """
        pass

    def test_update_tenant_variables(self):
        """Test case for update_tenant_variables

        """
        pass

    def test_update_tenant_variables_spaces(self):
        """Test case for update_tenant_variables_spaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
