# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.13.4+Branch.tags-2019.13.4.Sha.0d7b19b0ef3b9f74ec58e5c86ae6af95165ef70e
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.artifacts_api import ArtifactsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArtifactsApi(unittest.TestCase):
    """ArtifactsApi unit test stubs"""

    def setUp(self):
        self.api = api.artifacts_api.ArtifactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_artifact(self):
        """Test case for create_artifact

        Create a ArtifactResource  # noqa: E501
        """
        pass

    def test_create_artifact_spaces(self):
        """Test case for create_artifact_spaces

        Create a ArtifactResource  # noqa: E501
        """
        pass

    def test_delete_artifact(self):
        """Test case for delete_artifact

        Delete a ArtifactResource by ID  # noqa: E501
        """
        pass

    def test_delete_artifact_spaces(self):
        """Test case for delete_artifact_spaces

        Delete a ArtifactResource by ID  # noqa: E501
        """
        pass

    def test_get_artifact_by_id(self):
        """Test case for get_artifact_by_id

        Get a ArtifactResource by ID  # noqa: E501
        """
        pass

    def test_get_artifact_by_id_spaces(self):
        """Test case for get_artifact_by_id_spaces

        Get a ArtifactResource by ID  # noqa: E501
        """
        pass

    def test_get_artifact_content(self):
        """Test case for get_artifact_content

        """
        pass

    def test_get_artifact_content_spaces(self):
        """Test case for get_artifact_content_spaces

        """
        pass

    def test_index_artifacts(self):
        """Test case for index_artifacts

        Get a list of ArtifactResources  # noqa: E501
        """
        pass

    def test_index_artifacts_spaces(self):
        """Test case for index_artifacts_spaces

        Get a list of ArtifactResources  # noqa: E501
        """
        pass

    def test_update_artifact(self):
        """Test case for update_artifact

        Modify a ArtifactResource by ID  # noqa: E501
        """
        pass

    def test_update_artifact_content(self):
        """Test case for update_artifact_content

        """
        pass

    def test_update_artifact_content_spaces(self):
        """Test case for update_artifact_content_spaces

        """
        pass

    def test_update_artifact_spaces(self):
        """Test case for update_artifact_spaces

        Modify a ArtifactResource by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
